# Configurations
title:            Technical Blog 
longtitle:        Contravia Technical Blog
author:           seo
email:            
description: >
  Build Jekyll site with the GitBook style~
version:          
gitbook_version:  

url:              'https://contravia-cloud.github.io/TechnicalBlog'
baseurl:          
rss:              RSS

toc:
  enabled: true
  h_min: 1
  h_max: 3

# markdown render engine.
markdown:         kramdown
# kramdown : markdown의 개조판.
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# MathJax 적용
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jemoji
